-- Time to Surf final patch: session order, translated leaders, fixed text
-- Generated 2026-06-18. Run after the full schema SQL, or on the current Supabase database.
set client_encoding = 'UTF8';
alter table public.camp_sessions add column if not exists sort_order int not null default 0;
alter table public.camp_sessions add column if not exists leaders_ru text default '';
alter table public.camp_sessions add column if not exists leaders_en text default '';
alter table public.camp_sessions add column if not exists leaders_et text default '';
update public.camp_sessions set leaders='Наташа К. + Даша', leaders_ru='Наташа К. + Даша', leaders_en='Natasha K. + Dasha', leaders_et='Natasha K. + Dasha', sort_order=1 where dates='15.06 - 19.06.2026';
update public.camp_sessions set leaders='Наташа К. + Даша', leaders_ru='Наташа К. + Даша', leaders_en='Natasha K. + Dasha', leaders_et='Natasha K. + Dasha', sort_order=2 where dates='29.06 - 03.07.2026';
update public.camp_sessions set leaders='Надежда + Григорий', leaders_ru='Надежда + Григорий', leaders_en='Nadezhda + Grigory', leaders_et='Nadezhda + Grigory', sort_order=3 where dates='06.07 - 10.07.2026';
update public.camp_sessions set leaders='Виталий + Григорий', leaders_ru='Виталий + Григорий', leaders_en='Vitaliy + Grigory', leaders_et='Vitaliy + Grigory', sort_order=4 where dates='13.07 - 17.07.2026';
update public.camp_sessions set leaders='Надежда + Ксения', leaders_ru='Надежда + Ксения', leaders_en='Nadezhda + Kseniya', leaders_et='Nadezhda + Kseniya', sort_order=5 where dates='20.07 - 24.07.2026';
update public.camp_sessions set leaders='TBD', leaders_ru='TBD', leaders_en='TBD', leaders_et='TBD', sort_order=6 where dates='27.07 - 30.07.2026';
update public.camp_sessions set leaders='Даша + ...', leaders_ru='Даша + ...', leaders_en='Dasha + ...', leaders_et='Dasha + ...', sort_order=7 where dates='03.08 - 07.08.2026';
update public.camp_sessions set leaders='Надежда + ...', leaders_ru='Надежда + ...', leaders_en='Nadezhda + ...', leaders_et='Nadezhda + ...', sort_order=8 where dates='10.08 - 14.08.2026';
update public.camp_sessions set leaders='Виталий + ...', leaders_ru='Виталий + ...', leaders_en='Vitaliy + ...', leaders_et='Vitaliy + ...', sort_order=9 where dates='17.08 - 21.08.2026';

-- Fixed site text rows: no mojibake, no broken emoji in day schedule, fixed Estonian strings.
insert into public.site_content (key,label,group_name,value_ru,value_en,value_et,sort_order) values
  ('text_001', 'На воде', 'Галерея / секции', 'На воде', 'On the water', 'Vees', 1),
  ('text_002', 'Команда и берег', 'Галерея / секции', 'Команда и берег', 'Team and shore', 'Tiim ja rand', 2),
  ('text_003', 'На воде', 'Галерея / секции', 'На воде', 'On the Water', 'Vees', 3),
  ('text_004', 'Команда и атмосфера', 'Галерея / секции', 'Команда и атмосфера', 'Team & Vibes', 'Meeskond ja atmosfäär', 4),
  ('text_005', 'Моменты', 'Галерея / секции', 'Моменты', 'Moments', 'Hetked', 5),
  ('text_006', 'СЕРФИНГ + КИНО', 'Смены / расписание', 'СЕРФИНГ + КИНО', 'SURF + CINEMA', 'SURF + KINO', 6),
  ('text_007', 'Наташа К. + Даша', 'Смены / расписание', 'Наташа К. + Даша', 'Natasha K. + Dasha', 'Natasha K. + Dasha', 7),
  ('text_008', 'СЕРФИНГ + КИНО', 'Смены / расписание', 'СЕРФИНГ + КИНО', 'SURF + CINEMA', 'SURF + KINO', 8),
  ('text_009', 'Наташа К. + Даша', 'Смены / расписание', 'Наташа К. + Даша', 'Natasha K. + Dasha', 'Natasha K. + Dasha', 9),
  ('text_010', 'СЕРФИНГ ЛАГЕРЬ', 'Смены / расписание', 'СЕРФИНГ ЛАГЕРЬ', 'SURF CAMP', 'SURFI LAAGER', 10),
  ('text_011', 'Надежда + Григорий', 'Смены / расписание', 'Надежда + Григорий', 'Nadezhda + Grigory', 'Nadezhda + Grigory', 11),
  ('text_012', 'СЕРФИНГ + ПОХОД', 'Смены / расписание', 'СЕРФИНГ + ПОХОД', 'SURF + HIKE', 'SURF + MATK', 12),
  ('text_013', 'Виталий + Григорий', 'Смены / расписание', 'Виталий + Григорий', 'Vitaliy + Grigory', 'Vitaliy + Grigory', 13),
  ('text_014', 'СЕРФИНГ ЛАГЕРЬ', 'Смены / расписание', 'СЕРФИНГ ЛАГЕРЬ', 'SURF CAMP', 'SURFI LAAGER', 14),
  ('text_015', 'Надежда + Ксения', 'Смены / расписание', 'Надежда + Ксения', 'Nadezhda + Kseniya', 'Nadezhda + Kseniya', 15),
  ('text_016', 'СЕРФИНГ (4 ДНЯ)', 'Смены / расписание', 'СЕРФИНГ (4 ДНЯ)', 'SURF (4 DAYS)', 'SURF (4 PAEVA)', 16),
  ('text_017', 'СЕРФИНГ ЛАГЕРЬ', 'Смены / расписание', 'СЕРФИНГ ЛАГЕРЬ', 'SURF CAMP', 'SURFI LAAGER', 17),
  ('text_018', 'Даша + ...', 'Смены / расписание', 'Даша + ...', 'Dasha + ...', 'Dasha + ...', 18),
  ('text_019', 'СЕРФИНГ ЛАГЕРЬ', 'Смены / расписание', 'СЕРФИНГ ЛАГЕРЬ', 'SURF CAMP', 'SURFI LAAGER', 19),
  ('text_020', 'Надежда + ...', 'Смены / расписание', 'Надежда + ...', 'Nadezhda + ...', 'Nadezhda + ...', 20),
  ('text_021', 'СЕРФИНГ + ПОХОД', 'Смены / расписание', 'СЕРФИНГ + ПОХОД', 'SURF + HIKE', 'SURF + MATK', 21),
  ('text_022', 'Виталий + ...', 'Смены / расписание', 'Виталий + ...', 'Vitaliy + ...', 'Vitaliy + ...', 22),
  ('text_023', 'Нужен ли опыт серфинга?', 'FAQ', 'Нужен ли опыт серфинга?', 'Is surfing experience required?', 'Kas surfikogemus on vajalik?', 23),
  ('text_024', 'Нет, лагерь подходит полным новичкам - учим с нуля. Дети с опытом тоже найдут задачу по уровню.', 'FAQ', 'Нет, лагерь подходит полным новичкам - учим с нуля. Дети с опытом тоже найдут задачу по уровню.', 'No. The camp suits complete beginners - we teach from scratch. Experienced kids find their challenge too.', 'Ei. Laager sobib algajatele - õpetame nullist.', 24),
  ('text_025', 'Какой возраст подходит?', 'FAQ', 'Какой возраст подходит?', 'What age is suitable?', 'Mis vanus sobib?', 25),
  ('text_026', 'Основная программа для детей ...', 'FAQ', 'Основная программа для детей 7-12 лет. Возможно участие помладше, если справляется с программой. Максимум - 14 лет.', 'Main programme for ages 7-12. Younger children may attend if capable. Maximum age 14.', 'Põhiprogramm on 7-12-aastastele. Maksimaalne vanus 14.', 26),
  ('text_027', 'Что входит в стоимость?', 'FAQ', 'Что входит в стоимость?', 'What is included?', 'Mis on hinnas sees?', 27),
  ('text_028', 'Вся программа, питание от Tark Ca...', 'FAQ', 'Вся программа, питание от Tark Catering (обед + полдник), гидрокостюмы, спасательные жилеты, всё оборудование, работа инструкторов и сертификат участника.', 'Full programme, meals (lunch + snack, Tark Catering), wetsuits, life jackets, all equipment, instructors, certificate.', 'Kogu programm, toitlustus (Tark Catering), märjaksüidid, päästevested, varustus, sertifikaat.', 28),
  ('text_029', 'Что взять с собой?', 'FAQ', 'Что взять с собой?', 'What to bring?', 'Mida kaasa võtta?', 29),
  ('text_030', 'Сменную одежду, полотенце, солнцезащитный крем и бутылку воды. Гидрокостюм и оборудование - от нас.', 'FAQ', 'Сменную одежду, полотенце, солнцезащитный крем и бутылку воды. Гидрокостюм и оборудование - от нас.', 'Change of clothes, towel, sunscreen, water bottle. Wetsuit and equipment provided.', 'Vahetusriided, rätik, päikesekaitsevahend, veepudel. Märjaksüit ja varustus meie käest.', 30),
  ('text_031', 'Что если плохая погода?', 'FAQ', 'Что если плохая погода?', 'What if the weather is bad?', 'Mis saab halva ilmaga?', 31),
  ('text_032', 'Работаем в любую погоду - для этого и нужны гидрокостюмы! При реальной угрозе безопасности программа переходит на берег.', 'FAQ', 'Работаем в любую погоду - для этого и нужны гидрокостюмы! При реальной угрозе безопасности программа переходит на берег.', 'We work in any weather - that''s what wetsuits are for! Real safety risk -> shore programme.', 'Töötame igasuguse ilmaga! Reaalse ohu korral programm kaldale.', 32),
  ('text_033', 'Учитываются ли аллергии?', 'FAQ', 'Учитываются ли аллергии?', 'Are allergies accommodated?', 'Kas allergiad arvestatakse?', 33),
  ('text_034', 'Да, каждый ребёнок получает порцию с учётом питания. Укажите аллергии при регистрации.', 'FAQ', 'Да, каждый ребёнок получает порцию с учётом питания. Укажите аллергии при регистрации.', 'Yes. Individual portions, noting dietary needs. Note allergies at registration.', 'Jah. Individuaalsed portsjonid. Märkige allergiad registreerimisel.', 34),
  ('text_035', 'Можно на 3-4 дня?', 'FAQ', 'Можно на 3-4 дня?', 'Can we attend 3-4 days?', 'Kas saab 3-4 päevaks?', 35),
  ('text_036', 'Да! 3 дня - 190€, 4 дня - 235€. Укажите при регистрации.', 'FAQ', 'Да! 3 дня - 190€, 4 дня - 235€. Укажите при регистрации.', 'Yes! 3 days €190, 4 days €235. Specify at registration.', 'Jah! 3 päeva 190€, 4 päeva 235€. Märkige see registreerimisel.', 36),
  ('text_037', 'Как обеспечивается безопасно...', 'FAQ', 'Как обеспечивается безопасность на воде?', 'How is water safety ensured?', 'Kuidas veeohutus tagatakse?', 37),
  ('text_038', 'Все дети в воде - только в жиле...', 'FAQ', 'Все дети в воде - только в жилете и гидрокостюме. Группы 12-16 человек, постоянный контроль, обязательная теория безопасности перед каждым заходом.', 'All children in the water only with life jacket and wetsuit. Groups 12-16, constant supervision, mandatory safety theory before every session.', 'Kõik lapsed vees ainult päästevesti ja märjaksüidiga. Grupid 12-16, pidev järelevalve.', 38),
  ('text_039', 'Серфинг + Кино', 'Модалки программ', 'Серфинг + Кино', 'Surf + Cinema', 'Surf + Kino', 39),
  ('text_040', 'Лагерь, где дети не просто отд...', 'Модалки программ', 'Лагерь, где дети не просто отдыхают - а становятся героями своего фильма. 5 дней приключений.', 'A camp where kids don''t just rest - they become heroes of their own film. 5 days of adventure.', 'Laager, kus lapsed ei puhka lihtsalt - nad saavad oma filmi kangelasteks. 5 päeva seiklusi.', 40),
  ('text_041', '7-12 лет', 'Модалки программ', '7-12 лет', '7-12 years', '7-12 aastat', 41),
  ('text_042', 'Серфинг и активность', 'Модалки программ', 'Серфинг и активность', 'Surfing & Activity', 'Surfamine ja aktiivsus', 42),
  ('text_043', 'SUP-серфинг, баланс, координаци...', 'Модалки программ', 'SUP-серфинг, баланс, координация и ОФП каждый день', 'SUP surfing, balance, coordination and fitness every day', 'SUP-surf, tasakaal, koordinatsioon ja üldfüüsiline ettevalmistus iga päev', 43),
  ('text_044', 'Игры на пляже', 'Модалки программ', 'Игры на пляже', 'Beach games', 'Rannamängud', 44),
  ('text_045', 'Безопасность на воде - важный ...', 'Модалки программ', 'Безопасность на воде - важный блок', 'Water safety - a key module', 'Veeohutus - oluline osa', 45),
  ('text_046', 'Учимся лучше чувствовать себя рядом со стихиями', 'Модалки программ', 'Учимся лучше чувствовать себя рядом со стихиями', 'Learning to feel at ease with nature', 'Opime end looduse juures paremini tundma', 46),
  ('text_047', 'Создание фильма', 'Модалки программ', 'Создание фильма', 'Film Making', 'Filmi loomine', 47),
  ('text_048', 'Ведущие - снимают репортажи и ...', 'Модалки программ', 'Ведущие - снимают репортажи и берут интервью', 'Hosts - shoot reports and conduct interviews', 'Saatejuhid - teevad reportaaeze ja intervjuusid', 48),
  ('text_049', 'Операторы - учатся видеть детали и кадры', 'Модалки программ', 'Операторы - учатся видеть детали и кадры', 'Cameramen - learn to see details and frames', 'Operaatorid - õpivad nägema detaile ja kaadreid', 49),
  ('text_050', 'Монтажёры - собирают видео простым и понятным способом', 'Модалки программ', 'Монтажёры - собирают видео простым и понятным способом', 'Editors - assemble video simply and clearly', 'Monteerijad - koostavad video lihtsalt ja selgelt', 50),
  ('text_051', 'Креативная команда - идеи, сце...', 'Модалки программ', 'Креативная команда - идеи, сцены, эмоции', 'Creative team - ideas, scenes, emotions', 'Loominguline meeskond - ideed, stseenid, emotsioonid', 51),
  ('text_052', 'Что снимаем', 'Модалки программ', 'Что снимаем', 'What we film', 'Mida filmime', 52),
  ('text_053', '"Новости лагеря" каждый день', 'Модалки программ', '"Новости лагеря" каждый день', '"Camp News" every day', '"Laagri uudised" iga paev', 53),
  ('text_054', 'Смешные и живые моменты', 'Модалки программ', 'Смешные и живые моменты', 'Funny and lively moments', 'Naljakad ja elavad hetked', 54),
  ('text_055', 'Сцены в воде - брызги, эмоции, движение', 'Модалки программ', 'Сцены в воде - брызги, эмоции, движение', 'Water scenes - splashes, emotions, movement', 'Veestseenid - pritsmeid, emotsioone, liikumist', 55),
  ('text_056', 'Дружба, команда, впечатления', 'Модалки программ', 'Дружба, команда, впечатления', 'Friendship, teamwork, impressions', 'Soprus, meeskond, muljed', 56),
  ('text_057', 'Результат', 'Модалки программ', 'Результат', 'Result', 'Tulemus', 57),
  ('text_058', 'Короткий фильм, который остан...', 'Модалки программ', 'Короткий фильм, который останется вам на память', 'A short film to keep as a memory', 'Lühifilm, mis jääb teile mälestuseks', 58),
  ('text_059', 'Опыт выступления перед камерой', 'Модалки программ', 'Опыт выступления перед камерой', 'Experience performing in front of a camera', 'Kogemus kaamera ees esinemisest', 59),
  ('text_060', 'Новые навыки и уверенность', 'Модалки программ', 'Новые навыки и уверенность', 'New skills and confidence', 'Uued oskused ja enesekindlus', 60),
  ('text_061', 'Воспоминания, которые они реа...', 'Модалки программ', 'Воспоминания, которые они реально проживут', 'Memories they will truly live', 'Mälestused, mida nad päriselt kogevad', 61),
  ('text_062', 'Наталья Карасёва', 'Модалки программ', 'Наталья Карасёва', 'Natalia Karaseva', 'Natalia Karaseva', 62),
  ('text_063', 'Тележурналист, 20 лет на ТВ в двух странах, автор подкаста "Cozy with Tasha", создатель видеоконтента и документального короткого жанра.', 'Модалки программ', 'Тележурналист, 20 лет на ТВ в двух странах, автор подкаста "Cozy with Tasha", создатель видеоконтента и документального короткого жанра.', 'TV journalist, 20 years on TV in two countries, podcast "Cozy with Tasha", creator of video content and documentary short films.', 'Teleajakirjanik, 20 aastat televisioonis kahes riigis, taskuhaalingu "Cozy with Tasha" autor, videofilmide looja.', 63),
  ('text_064', 'Серфинг + Поход', 'Модалки программ', 'Серфинг + Поход', 'Surf + Hike', 'Surf + Matk', 64),
  ('text_065', 'Приключенческая программа, где ребёнок открывает мир серфинга и учится жить в природе.', 'Модалки программ', 'Приключенческая программа, где ребёнок открывает мир серфинга и учится жить в природе.', 'An adventure programme where the child discovers surfing and learns to live in nature.', 'Seiklusprogramm, kus laps avastab surfimaailma ja õpib looduses hakkama saama.', 65),
  ('text_066', '7-14 лет', 'Модалки программ', '7-14 лет', '7-14 years', '7-14 aastat', 66),
  ('text_067', 'Серфинг-часть', 'Модалки программ', 'Серфинг-часть', 'Surf part', 'Surfiosa', 67),
  ('text_068', 'Виндсерфинг, SUP-серфинг, вингф...', 'Модалки программ', 'Виндсерфинг, SUP-серфинг, вингфоилинг', 'Windsurfing, SUP surfing, wingfoiling', 'Purjelaud, SUP surfamine, wingfoiling', 68),
  ('text_069', 'Бодиборд', 'Модалки программ', 'Бодиборд', 'Bodyboard', 'Bodybord', 69),
  ('text_070', 'Знакомство с гидрокостюмами и уход за ними', 'Модалки программ', 'Знакомство с гидрокостюмами и уход за ними', 'Introduction to wetsuits and their care', 'Märjaksüütide tutvustus ja hooldamine', 70),
  ('text_071', 'Безопасность, чтение ветра и природы', 'Модалки программ', 'Безопасность, чтение ветра и природы', 'Safety, reading wind and nature', 'Ohutus, tuule ja looduse lugemine', 71),
  ('text_072', 'Походная часть', 'Модалки программ', 'Походная часть', 'Hiking part', 'Matkaosa', 72),
  ('text_073', 'Ориентирование по карте и ком...', 'Модалки программ', 'Ориентирование по карте и компасу', 'Map and compass navigation', 'Kaardi ja kompassiga orienteerumine', 73),
  ('text_074', 'Навыки поведения в лесу', 'Модалки программ', 'Навыки поведения в лесу', 'Forest survival skills', 'Metsas käitumise oskused', 74),
  ('text_075', 'Сборка палатки и организация ...', 'Модалки программ', 'Сборка палатки и организация лагеря', 'Setting up a tent and organising camp', 'Telgi püstitamine ja laagri korraldamine', 75),
  ('text_076', 'Разведение костра и базовые н...', 'Модалки программ', 'Разведение костра и базовые навыки выживания', 'Making a fire and basic survival skills', 'Lõkke tegemine ja baasoskused looduses', 76),
  ('text_077', 'Финал - настоящий мини-поход с...', 'Модалки программ', 'Финал - настоящий мини-поход с применением всех навыков', 'Finale - a real mini-hike applying all skills', 'Finaal - paris minimatk koigi oskustega', 77),
  ('text_078', 'Что получает ребёнок', 'Модалки программ', 'Что получает ребёнок', 'What the child gains', 'Mida laps saab', 78),
  ('text_079', 'Уверенность на воде и в природе', 'Модалки программ', 'Уверенность на воде и в природе', 'Confidence in water and in nature', 'Enesekindlus vees ja looduses', 79),
  ('text_080', 'Умение ориентироваться и принимать решения', 'Модалки программ', 'Умение ориентироваться и принимать решения', 'Ability to navigate and make decisions', 'Oskus orienteeruda ja otsuseid teha', 80),
  ('text_081', 'Самостоятельность и осознанн...', 'Модалки программ', 'Самостоятельность и осознанность', 'Independence and mindfulness', 'Iseseisvus ja teadlikkus', 81),
  ('text_082', 'Нашивку походника Time to Surf', 'Модалки программ', 'Нашивку походника Time to Surf', 'Time to Surf hiker patch', 'Time to Surf matkaja embleem', 82),
  ('text_083', 'Виталий Холстинин', 'Модалки программ', 'Виталий Холстинин', 'Vitaliy Kholstinin', 'Vitaliy Kholstinin', 83),
  ('text_084', 'Предприниматель, хайкер, осно...', 'Модалки программ', 'Предприниматель, хайкер, основатель Join The Hike. Более 10 лет опыта. Höga Kusten 140 км (UNESCO), Land of Giants 120 км. Живёт тем, что преподаёт.', 'Entrepreneur, hiker, founder of Join The Hike. 10+ years experience. Höga Kusten 140km (UNESCO), Land of Giants 120km. Lives what he teaches.', 'Ettevotja, matkaja, Join The Hike asutaja. 10+ aastat kogemust. Höga Kusten 140km (UNESCO), Land of Giants 120km. Elab seda, mida opetab.', 84),
  ('text_085', 'Серфинг лагерь', 'Модалки программ', 'Серфинг лагерь', 'Surf Camp', 'Surfilaager', 85),
  ('text_086', 'Классическая программа для тех, кто впервые открывает мир серфинга. Разные виды водного спорта, безопасность и командные игры.', 'Модалки программ', 'Классическая программа для тех, кто впервые открывает мир серфинга. Разные виды водного спорта, безопасность и командные игры.', 'The classic programme for those discovering surfing for the first time. Different water sports, safety and team games.', 'Klassikaline programm neile, kes avastavad surfimaailma esimest korda. Erinevad veespordialad, ohutus ja meeskonnamängud.', 86),
  ('text_087', '7-12 лет', 'Модалки программ', '7-12 лет', '7-12 years', '7-12 aastat', 87),
  ('text_088', 'Знакомство с миром серфинга', 'Модалки программ', 'Знакомство с миром серфинга', 'Discovering surfing', 'Surfimaailma avastamine', 88),
  ('text_089', 'Кайтсерфинг', 'Модалки программ', 'Кайтсерфинг', 'Kitesurfing', 'Kaidisurfamine', 89),
  ('text_090', 'Виндсерфинг', 'Модалки программ', 'Виндсерфинг', 'Windsurfing', 'Purjelaud', 90),
  ('text_091', 'SUP-серфинг', 'Модалки программ', 'SUP-серфинг', 'SUP surfing', 'SUP surfamine', 91),
  ('text_092', 'Вингфоилинг', 'Модалки программ', 'Вингфоилинг', 'Wingfoiling', 'Wingfoiling', 92),
  ('text_093', 'Бодиборд', 'Модалки программ', 'Бодиборд', 'Bodyboard', 'Bodybord', 93),
  ('text_094', 'Культура серфинга', 'Модалки программ', 'Культура серфинга', 'Surf culture', 'Surfikultuur', 94),
  ('text_095', 'Какие бывают гидрокостюмы', 'Модалки программ', 'Какие бывают гидрокостюмы', 'Types of wetsuits', 'Millised märjaksüüdid olemas on', 95),
  ('text_096', 'Как правильно их надевать', 'Модалки программ', 'Как правильно их надевать', 'How to put them on correctly', 'Kuidas neid õigesti selga panna', 96),
  ('text_097', 'Как ухаживать, чтобы служили долго', 'Модалки программ', 'Как ухаживать, чтобы служили долго', 'How to care for them to last longer', 'Kuidas hooldada, et kestaksid kaua', 97),
  ('text_098', 'Командные игры и развитие', 'Модалки программ', 'Командные игры и развитие', 'Team games & development', 'Meeskonnamangud ja areng', 98),
  ('text_099', 'Работа в команде', 'Модалки программ', 'Работа в команде', 'Teamwork', 'Meeskonnatok', 99),
  ('text_100', 'Поддержка друг друга', 'Модалки программ', 'Поддержка друг друга', 'Supporting each other', 'Üksteise toetamine', 100),
  ('text_101', 'Правила безопасности на воде', 'Модалки программ', 'Правила безопасности на воде', 'Water safety rules', 'Veeohutuse reeglid', 101),
  ('text_102', 'Понимание ветра, погоды и природы', 'Модалки программ', 'Понимание ветра, погоды и природы', 'Understanding wind, weather and nature', 'Tuule, ilma ja looduse mõistmine', 102),
  ('text_103', 'Результат', 'Модалки программ', 'Результат', 'Result', 'Tulemus', 103),
  ('text_104', 'Реальный прогресс и уверенность на воде', 'Модалки программ', 'Реальный прогресс и уверенность на воде', 'Real progress and confidence in water', 'Tegelik areng ja enesekindlus vees', 104),
  ('text_105', 'Развитие командного мышления', 'Модалки программ', 'Развитие командного мышления', 'Team thinking development', 'Meeskonnamotlemise arendamine', 105),
  ('text_106', 'Навыки безопасного поведения', 'Модалки программ', 'Навыки безопасного поведения', 'Safe behaviour skills', 'Ohutu käitumise oskused', 106),
  ('text_107', 'Сертификат участника', 'Модалки программ', 'Сертификат участника', 'Participation certificate', 'Osalussertifikaat', 107),
  ('text_108', 'Надежда + Григорий', 'Модалки программ', 'Надежда + Григорий', 'Nadezhda + Grigory', 'Nadezhda + Grigory', 108),
  ('text_109', 'Сертифицированные инструктора с многолетним опытом работы с детьми на Балтийском море. Умеют мотивировать и поддерживать на каждом этапе.', 'Модалки программ', 'Сертифицированные инструктора с многолетним опытом работы с детьми на Балтийском море. Умеют мотивировать и поддерживать на каждом этапе.', 'Certified instructors with years of experience working with children on the Baltic Sea. They know how to motivate and support at every stage.', 'Sertifitseeritud juhendajad, kellel on aastatepikkune kogemus lastega Läänemerel. Nad oskavad motiveerida ja igal etapil toetada.', 109),
  ('text_110', 'Программа', 'Модалка UI', 'Программа', 'Programme', 'Programm', 110),
  ('text_111', 'Возраст', 'Модалка UI', 'Возраст', 'Age', 'Vanus', 111),
  ('text_112', 'Стоимость', 'Модалка UI', 'Стоимость', 'Price', 'Hind', 112),
  ('text_113', 'всё включено', 'Модалка UI', 'всё включено', 'all included', 'kõik sees', 113),
  ('text_114', '5 дней - всё включено', 'Модалка UI', '5 дней - всё включено', '5 days - all included', '5 päeva - kõik hinnas', 114),
  ('text_115', 'Детские лагеря - Таллин', 'Hero / доверие', 'Детские лагеря - Таллин', 'Kids Camps - Tallinn', 'Laste laagrid - Tallinn', 115),
  ('text_116', 'Программы', 'Hero / доверие', 'Программы', 'Programmes', 'Programmid', 116),
  ('text_117', 'Цены', 'Hero / доверие', 'Цены', 'Prices', 'Hinnad', 117),
  ('text_118', 'Расписание', 'Hero / доверие', 'Расписание', 'Schedule', 'Ajakava', 118),
  ('text_119', 'Команда', 'Hero / доверие', 'Команда', 'Team', 'Meeskond', 119),
  ('text_120', 'Отзывы', 'Hero / доверие', 'Отзывы', 'Reviews', 'Arvustused', 120),
  ('text_121', 'Место', 'Hero / доверие', 'Место', 'Location', 'Asukoht', 121),
  ('text_122', 'Программы', 'Hero / доверие', 'Программы', 'Programmes', 'Programmid', 122),
  ('text_123', 'Цены', 'Hero / доверие', 'Цены', 'Prices', 'Hinnad', 123),
  ('text_124', 'Расписание', 'Hero / доверие', 'Расписание', 'Schedule', 'Ajakava', 124),
  ('text_125', 'Команда', 'Hero / доверие', 'Команда', 'Team', 'Meeskond', 125),
  ('text_126', 'Отзывы', 'Hero / доверие', 'Отзывы', 'Reviews', 'Arvustused', 126),
  ('text_127', 'Место', 'Hero / доверие', 'Место', 'Location', 'Asukoht', 127),
  ('text_128', 'Детский серфинг-лагерь - Stroomi r...', 'Hero / доверие', 'Детский серфинг-лагерь - Stroomi rand / Tallinn - Лето 2026', 'Kids surf camp - Stroomi Beach / Tallinn - Summer 2026', 'Laste surfilaager - Stroomi rand / Tallinn - Suvi 2026', 128),
  ('text_129', 'Лето, море и', 'Hero / доверие', 'Лето, море и', 'Summer, sea and', 'Suvi, meri ja', 129),
  ('text_130', 'серфинг для детей', 'Hero / доверие', 'серфинг для детей', 'surfing for kids', 'surf lastele', 130),
  ('text_131', '7-14 лет', 'Hero / доверие', '7-14 лет', 'ages 7-14', '7-14 aastat', 131),
  ('text_132', '5 дней на Stroomi rand: вода, спорт, д...', 'Hero / доверие', '5 дней на Stroomi rand: вода, спорт, друзья и свобода без телефона. Малые группы 12-16 детей, жилеты и гидрокостюмы, инструкторы рядом. Лето 2026, от 190€, места ограничены.', '5 days at Stroomi Beach: water, sport, friends and phone-free freedom. Small groups of 12-16 kids, life jackets, wetsuits and instructors close by. Summer 2026, from 190€, limited spots.', '5 päeva Stroomi rannas: vesi, sport, sõbrad ja telefonivaba vabadus. Väikesed grupid 12-16 last, päästevestid, märjaksüidid ja instruktorid kõrval. Suvi 2026, alates 190€, kohad piiratud.', 132),
  ('text_133', '7-14 лет', 'Hero / доверие', '7-14 лет', 'Ages 7-14', '7-14 aastat', 133),
  ('text_134', 'лето 2026', 'Hero / доверие', 'лето 2026', 'Summer 2026', 'Suvi 2026', 134),
  ('text_135', 'безопасность на воде', 'Hero / доверие', 'безопасность на воде', 'water safety', 'veeohutus', 135),
  ('text_136', 'места ограничены', 'Hero / доверие', 'места ограничены', 'limited spots', 'kohad piiratud', 136),
  ('text_137', 'Записать ребёнка', 'Hero / доверие', 'Записать ребёнка', 'Register my child', 'Registreeri laps', 137),
  ('text_138', 'Задать вопрос', 'Hero / доверие', 'Задать вопрос', 'Ask a question', 'Küsi küsimus', 138),
  ('text_139', 'Форматы лагерей 2026', 'Hero / доверие', 'Форматы лагерей 2026', 'Camp Formats 2026', 'Laagri formaadid 2026', 139),
  ('text_140', 'Серфинг + Кино', 'Hero / доверие', 'Серфинг + Кино', 'Surf + Cinema', 'Surf + Kino', 140),
  ('text_141', 'Серфинг + Поход', 'Hero / доверие', 'Серфинг + Поход', 'Surf + Hike', 'Surf + Matk', 141),
  ('text_142', 'Серфинг лагерь', 'Hero / доверие', 'Серфинг лагерь', 'Surf Camp', 'Surfilaager', 142),
  ('text_143', 'лет опыта', 'Hero / доверие', 'лет опыта', 'yrs experience', 'aastat kogemust', 143),
  ('text_144', '5 дней', 'Hero / доверие', '5 дней', '5 days', '5 päeva', 144),
  ('text_145', 'смен летом', 'Hero / доверие', 'смен летом', 'sessions/summer', 'vahetust suvel', 145),
  ('text_146', 'Почему родители выбирают нас', 'Hero / доверие', 'Почему родители выбирают нас', 'Why parents choose us', 'Miks vanemad valivad meid', 146),
  ('text_147', 'Time to Surf -', 'Hero / доверие', 'Time to Surf -', 'Time to Surf -', 'Time to Surf -', 147),
  ('text_148', 'не просто лагерь', 'Hero / доверие', 'не просто лагерь', 'more than a camp', 'rohkem kui laager', 148),
  ('text_149', 'Ребёнок проводит неделю на пл...', 'Hero / доверие', 'Ребёнок проводит неделю на пляже, в движении и под присмотром. Пробует SUP, виндсёрфинг, бодиборд и игры на воде, меньше сидит в телефоне, становится смелее и быстро находит друзей.', 'A week on the beach, active and supervised. Kids try SUP, windsurfing, bodyboard and water games, spend less time on phones, grow braver and make friends fast.', 'Nädal rannas, liikumises ja juhendajate silma all. Lapsed proovivad SUP-i, purjelauda, bodyboardi ja veemänge, on vähem telefonis, muutuvad julgemaks ja leiavad sõpru.', 149),
  ('text_150', 'лет опыта', 'Hero / доверие', 'лет опыта', 'years experience', 'aastat kogemust', 150),
  ('text_151', 'Мы давно работаем на воде и сп...', 'Hero / доверие', 'Мы давно работаем на воде и спокойно ведём детские группы.', 'We have years on the water and run kids groups calmly.', 'Oleme vees tegutsenud aastaid ja juhime laste gruppe rahulikult.', 151),
  ('text_152', 'рядом весь день', 'Hero / доверие', 'рядом весь день', 'near all day', 'kogu päeva kõrval', 152),
  ('text_153', 'Дети не остаются одни: на воде...', 'Hero / доверие', 'Дети не остаются одни: на воде, на берегу и во время игр за ними смотрят взрослые.', 'Kids are not left alone: adults watch them on water, on shore and during games.', 'Lapsed ei jää üksi: täiskasvanud jälgivad neid vees, kaldal ja mängude ajal.', 153),
  ('text_154', 'детей в группе', 'Hero / доверие', 'детей в группе', 'kids per group', 'last grupis', 154),
  ('text_155', 'Группа маленькая, поэтому инс...', 'Hero / доверие', 'Группа маленькая, поэтому инструктор видит каждого ребёнка.', 'The group is small, so the instructor sees every child.', 'Grupp on väike, nii näeb juhendaja iga last.', 155),
  ('text_156', 'и гидрокостюмы', 'Hero / доверие', 'и гидрокостюмы', 'and wetsuits', 'ja märjaksüidid', 156),
  ('text_157', 'В воду дети заходят только в ж...', 'Hero / доверие', 'В воду дети заходят только в жилете и гидрокостюме. Экипировка входит в цену.', 'Kids enter the water only in a life jacket and wetsuit. Gear is included.', 'Lapsed lähevad vette ainult päästevesti ja märjaksüüdiga. Varustus on hinnas.', 157),
  ('text_158', 'работы с детьми', 'Hero / доверие', 'работы с детьми', 'with children', 'lastega', 158),
  ('text_159', 'Объясняем просто, не торопим и помогаем тем, кто боится воды.', 'Hero / доверие', 'Объясняем просто, не торопим и помогаем тем, кто боится воды.', 'We explain simply, do not rush and help kids who are nervous around water.', 'Selgitame lihtsalt, ei kiirusta ja aitame lapsi, kes vett pelgavad.', 159),
  ('text_160', 'реальной команды', 'Hero / доверие', 'реальной команды', 'real team', 'päris tiimist', 160),
  ('text_161', 'Ниже - настоящие люди, которые...', 'Hero / доверие', 'Ниже - настоящие люди, которые работают с детьми на сменах.', 'Below are the real people working with kids during sessions.', 'Selgitame lihtsalt, ei kiirusta ja aitame lapsi, kes vett kardavad.', 161),
  ('text_162', 'перед каждым заходом', 'Hero / доверие', 'перед каждым заходом', 'before each session', 'enne igat sessiooni', 162),
  ('text_163', 'Перед водой повторяем: где стоять, что делать при ветре и как слушать инструктора.', 'Hero / доверие', 'Перед водой повторяем: где стоять, что делать при ветре и как слушать инструктора.', 'Before water we repeat where to stand, what to do in wind and how to listen.', 'Enne vette minekut kordame, kus olla, mida tuulega teha ja kuidas juhendajat kuulata.', 163),
  ('text_164', 'без телефона', 'Hero / доверие', 'без телефона', 'without the phone', 'ilma telefonita', 164),
  ('text_165', 'День занят делом: вода, еда, иг...', 'Hero / доверие', 'День занят делом: вода, еда, игры, команда и новые навыки.', 'The day is full: water, food, games, team and new skills.', 'Päev on sisukas: vesi, toit, mängud, tiim ja uued oskused.', 165),
  ('text_166', 'Безопасность', 'Безопасность', 'Безопасность', 'Safety', 'Ohutus', 166),
  ('text_167', 'Родителям', 'Безопасность', 'Родителям', 'Parents', 'Vanematele', 167),
  ('text_168', 'спокойно', 'Безопасность', 'спокойно', 'can relax', 'on rahulik', 168),
  ('text_169', 'Главное - чтобы ребёнок был за...', 'Безопасность', 'Главное - чтобы ребёнок был занят, доволен и под контролем. Мы заранее объясняем правила, выдаём жилеты и гидрокостюмы, а инструкторы постоянно держат группу в поле зрения.', 'The main thing: kids are active, happy and supervised. We explain rules first, give life jackets and wetsuits, and instructors keep the group in sight.', 'Peamine: laps on tegevuses, rahul ja jälgitud. Selgitame reeglid, anname päästevestid ja märjaksüidid ning juhendajad hoiavad gruppi silma all.', 169),
  ('text_170', 'Жилет на каждом ребёнке', 'Безопасность', 'Жилет на каждом ребёнке', 'Life jacket on every child', 'Päästevest igal lapsel', 170),
  ('text_171', 'На воде без жилета не работаем. Это правило для всех.', 'Безопасность', 'На воде без жилета не работаем. Это правило для всех.', 'No life jacket - no water session. This rule is for everyone.', 'Ilma päästevestita vette ei minda. See reegel kehtib kõigile.', 171),
  ('text_172', 'Гидрокостюм входит в цену', 'Безопасность', 'Гидрокостюм входит в цену', 'Wetsuit included', 'Märjaksüit hinnas', 172),
  ('text_173', 'Ребёнку теплее, комфортнее и проще дольше быть в воде.', 'Безопасность', 'Ребёнку теплее, комфортнее и проще дольше быть в воде.', 'Kids stay warmer, more comfortable and can spend longer in water.', 'Lapsel on soojem, mugavam ja lihtsam vees olla.', 173),
  ('text_174', 'Малые группы', 'Безопасность', 'Малые группы', 'Small groups', 'Instruktorid näevad lapsi vees, rannas ja mängude ajal.', 174),
  ('text_175', '12-16 детей - инструктор успевае...', 'Безопасность', '12-16 детей - инструктор успевает помочь каждому.', '12-16 kids - the instructor has time for each child.', '12-16 last - juhendajal on aega iga lapse jaoks.', 175),
  ('text_176', 'Опытная команда', 'Безопасность', 'Опытная команда', 'Experienced team', 'Kogenud tiim', 176),
  ('text_177', 'Инструкторы умеют работать с ...', 'Безопасность', 'Инструкторы умеют работать с детьми: объяснить, поддержать и вовремя остановить.', 'Instructors know children: how to explain, support and stop in time.', 'Juhendajad oskavad lastega töötada: selgitada, toetada ja õigel ajal peatada.', 177),
  ('text_178', 'Наши программы', 'Три программы', 'Наши программы', 'Our programmes', 'Meie programmid', 178),
  ('text_179', 'Три уникальные программы', 'Три программы', 'Три уникальные программы', 'Three unique programmes', 'Kolm ainulaadset programmi', 179),
  ('text_180', 'Во всех программах есть вода, ...', 'Три программы', 'Во всех программах есть вода, движение и работа в группе. Отличается вторая часть дня: кино, поход или классический серфинг.', 'Every programme has water, movement and group work. The second half of the day changes: cinema, hike or classic surf.', 'Igas programmis on vesi, liikumine ja grupitöö. Päeva teine pool on erinev: kino, matk või klassikaline surf.', 180),
  ('text_181', 'Серфинг + творчество', 'Три программы', 'Серфинг + творчество', 'Surfing + creativity', 'Surf + loovus', 181),
  ('text_182', 'Серфинг + Кино', 'Три программы', 'Серфинг + Кино', 'Surf + Cinema', 'Surf + Kino', 182),
  ('text_183', 'Утром - вода и серфинг. После о...', 'Три программы', 'Утром - вода и серфинг. После обеда дети пробуют роли ведущего, оператора, сценариста и монтажёра. В конце - короткий фильм для родителей.', 'Morning - water and surfing. After lunch kids try being host, camera operator, writer and editor. At the end - a short film for parents.', 'Hommikul - vesi ja surf. Pärast lõunat proovivad lapsed saatejuhi, operaatori, stsenaristi ja monteerija rolle. Lõpus - lühifilm vanematele.', 183),
  ('text_184', 'SUP, бодиборд и ОФП каждый день', 'Три программы', 'SUP, бодиборд и ОФП каждый день', 'SUP, bodyboard and fitness every day', 'SUP, bodyboard ja üldfüüsiline ettevalmistus iga päev', 184),
  ('text_185', 'Интервью и съёмки в команде', 'Три программы', 'Интервью и съёмки в команде', 'Interviews and filming in a team', 'Intervjuud ja filmimine tiimis', 185),
  ('text_186', 'Ведущая - Наталья Карасева, ТВ...', 'Три программы', 'Ведущая - Наталья Карасева, ТВ-журналист', 'Lead - Natalia Karaseva, TV journalist', 'Juhendaja - Natalia Karaseva, teleajakirjanik', 186),
  ('text_187', 'Серфинг + приключение', 'Три программы', 'Серфинг + приключение', 'Surfing + adventure', 'Surf + seiklus', 187),
  ('text_188', 'Серфинг + Поход', 'Три программы', 'Серфинг + Поход', 'Surf + Hike', 'Surf + Matk', 188),
  ('text_189', 'Вода, игры и простые походные ...', 'Три программы', 'Вода, игры и простые походные навыки: карта, компас, костёр, палатка. Подходит детям, которым хочется больше природы и движения.', 'Water, games and simple outdoor skills: map, compass, fire, tent. For kids who want more nature and movement.', 'Vesi, mängud ja lihtsad matkioskused: kaart, kompass, lõke, telk. Lastele, kes tahavad rohkem loodust ja liikumist.', 189),
  ('text_190', 'Виндсёрфинг, SUP и кайт', 'Три программы', 'Виндсёрфинг, SUP и кайт', 'Windsurfing, SUP and kite', 'Purjelaud, SUP ja lohesurf', 190),
  ('text_191', 'Ориентирование и командные задания', 'Три программы', 'Ориентирование и командные задания', 'Navigation and team tasks', 'Orienteerumine ja tiimiülesanded', 191),
  ('text_192', 'Ведущий - Виталий, Join The Hike', 'Три программы', 'Ведущий - Виталий, Join The Hike', 'Lead - Vitaliy, Join The Hike', 'Juhendaja - Vitaliy, Join The Hike', 192),
  ('text_193', 'Классика для старта', 'Три программы', 'Классика для старта', 'Classic first step', 'Klassika alustuseks', 193),
  ('text_194', 'Серфинг лагерь', 'Три программы', 'Серфинг лагерь', 'Surf Camp', 'Surfilaager', 194),
  ('text_195', 'Для первого знакомства с водо...', 'Три программы', 'Для первого знакомства с водой и доской. Дети пробуют разные водные виды спорта, учатся правилам безопасности и играют в команде.', 'A first step into water and boards. Kids try different water sports, learn safety rules and play as a team.', 'Esimene samm vee ja laua juurde. Lapsed proovivad eri veespordialasid, õpivad ohutust ja mängivad tiimis.', 195),
  ('text_196', 'SUP, виндсёрфинг, бодиборд', 'Три программы', 'SUP, виндсёрфинг, бодиборд', 'SUP, windsurfing, bodyboard', 'SUP, purjelaud, bodyboard', 196),
  ('text_197', 'Правила воды простым языком', 'Три программы', 'Правила воды простым языком', 'Water rules in simple words', 'Vee reeglid lihtsas keeles', 197),
  ('text_198', 'Подходит новичкам', 'Три программы', 'Подходит новичкам', 'Good for beginners', 'Sobib algajatele', 198),
  ('text_199', 'Подробнее', 'Три программы', 'Подробнее', 'Details', 'Loe lähemalt', 199),
  ('text_200', 'Программа дня', 'Программа дня', 'Программа дня', 'Day programme', 'Päevaprogramm', 200),
  ('text_201', 'Как проходит день', 'Программа дня', 'Как проходит день', 'How the day goes', 'Kuidas päev kulgeb', 201),
  ('text_202', 'Сбор детей', 'Программа дня', 'Сбор детей', 'Arrival', 'Kogunemine', 202),
  ('text_203', 'Встреча детей, знакомство, настрой на день', 'Программа дня', 'Встреча детей, знакомство, настрой на день', 'Meeting kids, introductions, setting the mood', 'Laste vastuvõtt, tutvumine, päevaks valmistumine', 203),
  ('text_204', 'Разминка', 'Программа дня', 'Разминка', 'Warm-up', 'Soojendus', 204),
  ('text_205', 'Активные тренировки и командные игры на берегу', 'Программа дня', 'Активные тренировки и командные игры на берегу', 'Active training and team games on shore', 'Aktiivsed treeningud ja meeskonnamängud kaldal', 205),
  ('text_206', 'Водный блок', 'Программа дня', 'Водный блок', 'Water block', 'Vesiplokk', 206),
  ('text_207', 'Теория безопасности, гидрокостюмы, SUP и виндсерфинг', 'Программа дня', 'Теория безопасности, гидрокостюмы, SUP и виндсерфинг', 'Safety theory, wetsuits, SUP and windsurfing', 'Ohutusteooria, märjaksüüdid, SUP ja purjelauasõit', 207),
  ('text_208', 'Обед', 'Программа дня', 'Обед', 'Lunch', 'Lõuna', 208),
  ('text_209', 'Индивидуальные порции с учётом аллергий. Питание от Tark Catering', 'Программа дня', 'Индивидуальные порции с учётом аллергий. Питание от Tark Catering', 'Individual portions, allergies noted - Tark Catering', 'Individuaalsed portsjonid allergiatega arvestades - Tark Catering', 209),
  ('text_210', 'Отдых после обеда', 'Программа дня', 'Отдых после обеда', 'After-lunch rest', 'Puhkus pärast lõunat', 210),
  ('text_211', 'Спокойные и настольные игры, свободное общение', 'Программа дня', 'Спокойные и настольные игры, свободное общение', 'Quiet games, free time, conversations', 'Rahulikud lauamängud ja vaba suhtlemine', 211),
  ('text_212', 'Активная программа', 'Программа дня', 'Активная программа', 'Active programme', 'Aktiivne programm', 212),
  ('text_213', 'Виндсёрфинг, кайт, SUP, поход, хайкинг или пляжные игры - зависит от погоды', 'Программа дня', 'Виндсёрфинг, кайт, SUP, поход, хайкинг или пляжные игры - зависит от погоды', 'Windsurfing, kite, SUP, hiking or beach games - depends on weather', 'Purjelaud, lohe, SUP, matk või rannamängud - sõltub ilmast', 213),
  ('text_214', 'Чаепитие', 'Программа дня', 'Чаепитие', 'Tea time', 'Tee aeg', 214),
  ('text_215', 'Перерыв, отдых, свободное общение', 'Программа дня', 'Перерыв, отдых, свободное общение', 'Break, rest, free conversation', 'Paus, puhkus ja vaba suhtlemine', 215),
  ('text_216', 'Спокойный блок', 'Программа дня', 'Спокойный блок', 'Calm block', 'Rahulik osa', 216),
  ('text_217', 'Игры, творчество, интеллектуа...', 'Программа дня', 'Игры, творчество, интеллектуальные задания', 'Games, creativity, intellectual tasks', 'Mängud, loovus ja mõtlemisülesanded', 217),
  ('text_218', 'До завтра!', 'Программа дня', 'До завтра!', 'See you tomorrow!', 'Homseni!', 218),
  ('text_219', 'Конец программы, ожидание род...', 'Программа дня', 'Конец программы, ожидание родителей', 'Programme ends, parents pick up', 'Programm lõpeb, vanemad tulevad järele', 219),
  ('text_220', 'Все смены', 'Все смены', 'Все смены', 'All sessions', 'Kõik vahetused', 220),
  ('text_221', 'Расписание лета 2026', 'Все смены', 'Расписание лета 2026', 'Summer 2026 schedule', 'Suve 2026 ajakava', 221),
  ('text_222', 'Выберите смену и записывайтесь - места ограничены, группы маленькие.', 'Все смены', 'Выберите смену и записывайтесь - места ограничены, группы маленькие.', 'Choose your session and register - spots are limited, groups are small.', 'Valige vahetus ja registreeruge - kohti on piiratud, grupid on väikesed.', 222),
  ('text_223', 'Укомплектована', 'Все смены', 'Укомплектована', 'Full', 'Täis', 223),
  ('text_224', 'Мест мало!', 'Все смены', 'Мест мало!', 'Few spots!', 'Kohti vähe!', 224),
  ('text_225', 'Подробнее', 'Все смены', 'Подробнее', 'Details', 'Loe lähemalt', 225),
  ('text_226', 'Стоимость', 'Цены', 'Стоимость', 'Pricing', 'Hinnad', 226),
  ('text_227', 'Прозрачные цены -', 'Цены', 'Прозрачные цены -', 'Transparent pricing -', 'Läbipaistvad hinnad -', 227),
  ('text_228', 'всё включено', 'Цены', 'всё включено', 'all included', 'kõik sees', 228),
  ('text_229', '3 ДНЯ', 'Цены', '3 ДНЯ', '3 DAYS', '3 PÄEVA', 229),
  ('text_230', 'Пробная смена', 'Цены', 'Пробная смена', 'Trial session', 'Proovisessioon', 230),
  ('text_231', 'Идеально для первого знакомства', 'Цены', 'Идеально для первого знакомства', 'Perfect for a first try', 'Ideaalne esimeseks tutvumiseks', 231),
  ('text_232', '5 ДНЕЙ', 'Цены', '5 ДНЕЙ', '5 DAYS', '5 PÄEVA', 232),
  ('text_233', 'Полная программа', 'Цены', 'Полная программа', 'Full programme', 'Täisprogramm', 233),
  ('text_234', 'Максимум впечатлений и навыков', 'Цены', 'Максимум впечатлений и навыков', 'Maximum impressions and skills', 'Maksimaalselt muljeid ja oskusi', 234),
  ('text_235', '4 ДНЯ', 'Цены', '4 ДНЯ', '4 DAYS', '4 PÄEVA', 235),
  ('text_236', 'Гибкий формат', 'Цены', 'Гибкий формат', 'Flexible format', 'Paindlik formaat', 236),
  ('text_237', 'Удобно для занятых семей', 'Цены', 'Удобно для занятых семей', 'Convenient for busy families', 'Mugav hõivatud peredele', 237),
  ('text_238', 'Самый популярный', 'Цены', 'Самый популярный', 'Most popular', 'Populaarseim', 238),
  ('text_239', 'Записать ребёнка', 'Цены', 'Записать ребёнка', 'Register my child', 'Registreeri laps', 239),
  ('text_240', 'В цену входит', 'Цены', 'В цену входит', 'Included in price', 'Hind sisaldab', 240),
  ('text_241', 'Вся программа серфинга', 'Цены', 'Вся программа серфинга', 'Full surf programme', 'Kogu surfi programm', 241),
  ('text_242', 'Питание от Tark Catering', 'Цены', 'Питание от Tark Catering', 'Meals - Tark Catering', 'Toitlustus - Tark Catering', 242),
  ('text_243', 'Гидрокостюмы и жилеты', 'Цены', 'Гидрокостюмы и жилеты', 'Wetsuits and life jackets', 'Märjaksüüdid ja päästevestid', 243),
  ('text_244', 'Всё оборудование', 'Цены', 'Всё оборудование', 'All equipment', 'Kogu varustus', 244),
  ('text_245', 'Работа инструкторов', 'Цены', 'Работа инструкторов', 'Instructor work', 'Instruktorite töö', 245),
  ('text_246', 'Мастер-классы и активности', 'Цены', 'Мастер-классы и активности', 'Workshops and activities', 'Töötoad ja tegevused', 246),
  ('text_247', 'Чаепитие и полдник', 'Цены', 'Чаепитие и полдник', 'Tea time and snack', 'Teeaeg ja vahepala', 247),
  ('text_248', 'Сертификат участника', 'Цены', 'Сертификат участника', 'Participation certificate', 'Osalussertifikaat', 248),
  ('text_249', 'Галерея', 'Галерея', 'Галерея', 'Gallery', 'Galerii', 249),
  ('text_250', 'Фото и видео со смен', 'Галерея', 'Фото и видео со смен', 'Photos and videos from camp', 'Fotod ja videod laagrist', 250),
  ('text_251', 'Компактно: несколько живых ка...', 'Галерея', 'Компактно: несколько живых кадров на странице, остальные фото можно открыть кликом.', 'Compact: a few real moments on the page, the rest opens by click.', 'Kompaktselt: mõned päris hetked lehel, ülejäänud avanevad klikiga.', 251),
  ('text_252', 'детский серфинг лагерь Time to Sur...', 'Галерея', 'детский серфинг лагерь Time to Surf на Stroomi rand', 'Time to Surf kids surf camp at Stroomi Beach', 'Time to Surf laste surfilaager Stroomi rannas', 252),
  ('text_253', 'Дети на воде', 'Галерея', 'Дети на воде', 'Kids on water', 'Lapsed vees', 253),
  ('text_254', 'Видео', 'Галерея', 'Видео', 'Video', 'Video', 254),
  ('text_255', 'детский серфинг лагерь Time to Sur...', 'Галерея', 'детский серфинг лагерь Time to Surf на Stroomi rand', 'Time to Surf kids surf camp at Stroomi Beach', 'Time to Surf laste surfilaager Stroomi rannas', 255),
  ('text_256', 'Фото', 'Галерея', 'Фото', 'Photo', 'Foto', 256),
  ('text_257', 'детский серфинг лагерь Time to Sur...', 'Галерея', 'детский серфинг лагерь Time to Surf на Stroomi rand', 'Time to Surf kids surf camp at Stroomi Beach', 'Time to Surf laste surfilaager Stroomi rannas', 257),
  ('text_258', 'Отзывы', 'Отзывы', 'Отзывы', 'Reviews', 'Arvustused', 258),
  ('text_259', 'Что говорят родители', 'Отзывы', 'Что говорят родители', 'What parents say', 'Mida vanemad ütlevad', 259),
  ('text_260', 'Настоящие отзывы родителей, ч...', 'Отзывы', 'Настоящие отзывы родителей, чьи дети уже побывали в лагере.', 'Real reviews from parents whose children have attended camp.', 'Päris arvustused vanematelt, kelle lapsed on laagris käinud.', 260),
  ('text_261', 'Спасибо! Отзыв отправлен на проверку.', 'Отзывы', 'Спасибо! Отзыв отправлен на проверку.', 'Thank you! Your review is pending approval.', 'Aitäh! Arvustus ootab kinnitamist.', 261),
  ('text_262', 'Оставить отзыв', 'Отзывы', 'Оставить отзыв', 'Leave a review', 'Jäta arvustus', 262),
  ('text_263', 'Ваше имя', 'Отзывы', 'Ваше имя', 'Your name', 'Teie nimi', 263),
  ('text_264', 'Мария К.', 'Отзывы', 'Мария К.', 'Maria K.', 'Maria K.', 264),
  ('text_265', 'Программа', 'Отзывы', 'Программа', 'Programme', 'Programm', 265),
  ('text_266', 'Серфинг + Кино', 'Отзывы', 'Серфинг + Кино', 'Surf + Cinema', 'Surf + Kino', 266),
  ('text_267', 'Оценка', 'Отзывы', 'Оценка', 'Rating', 'Hinnang', 267),
  ('text_268', 'Ваш отзыв', 'Отзывы', 'Ваш отзыв', 'Your review', 'Teie arvustus', 268),
  ('text_269', 'Расскажите о вашем опыте...', 'Отзывы', 'Расскажите о вашем опыте...', 'Tell us about your experience...', 'Rääkige oma kogemusest...', 269),
  ('text_270', 'Отправка...', 'Отзывы', 'Отправка...', 'Sending...', 'Saadan...', 270),
  ('text_271', 'Отправить отзыв', 'Отзывы', 'Отправить отзыв', 'Submit review', 'Saada arvustus', 271),
  ('text_272', 'Частые вопросы', 'Локация', 'Частые вопросы', 'Frequently asked', 'Korduma kippuvad', 272),
  ('text_273', 'Место проведения', 'Локация', 'Место проведения', 'Location', 'Asukoht', 273),
  ('text_274', 'Пляж Штромка, Таллин', 'Локация', 'Пляж Штромка, Таллин', 'Stroomi Beach, Tallinn', 'Stroomi rand, Tallinn', 274),
  ('text_275', 'Открыть в Google Maps', 'Локация', 'Открыть в Google Maps', 'Open in Google Maps', 'Ava Google Mapsis', 275),
  ('text_276', 'Адрес', 'Локация', 'Адрес', 'Address', 'Aadress', 276),
  ('text_277', 'Stroomi rand - конец пляжа, ближе к Р...', 'Локация', 'Stroomi rand - конец пляжа, ближе к Рокка-аль-Маре. Серфинг-станция Time to Surf.', 'Stroomi beach, end of the beach, near Rocca al Mare. Time to Surf surf station.', 'Stroomi rand, ranna lõpp, Rocca al Mare lähedal.', 277),
  ('text_278', 'Как добраться', 'Локация', 'Как добраться', 'Getting there', 'Kuidas jõuda', 278),
  ('text_279', 'Автобусы №40, 48 до остановки Str...', 'Локация', 'Автобусы №40, 48 до остановки Stroomi rand - около 20 минут от центра.', 'Buses 40, 48 to Stroomi rand stop - about 20 minutes from the city centre.', 'Bussid nr 40 ja 48 Stroomi rand peatuseni - umbes 20 minutit kesklinnast.', 279),
  ('text_280', 'Парковка', 'Локация', 'Парковка', 'Parking', 'Parkimine', 280),
  ('text_281', 'Бесплатная парковка у пляжа. В выходные может быть занята - приезжайте заранее.', 'Локация', 'Бесплатная парковка у пляжа. В выходные может быть занята - приезжайте заранее.', 'Free parking at the beach. Can be busy on weekends - arrive early.', 'Tasuta parkimine ranna juures. Nädalavahetusel võib parkla täis olla - tulge varem.', 281),
  ('text_282', 'Контакт', 'Локация', 'Контакт', 'Contact', 'Kontakt', 282),
  ('text_283', 'Лето 2026 - Таллин', 'CTA', 'Лето 2026 - Таллин', 'Summer 2026 - Tallinn', 'Suvi 2026 - Tallinn', 283),
  ('text_284', 'Места', 'CTA', 'Места', 'Spots are', 'Kohti on', 284),
  ('text_285', 'ограничены.', 'CTA', 'ограничены.', 'limited.', 'piiratud.', 285),
  ('text_286', 'Записывайтесь сейчас.', 'CTA', 'Записывайтесь сейчас.', 'Register now.', 'Registreeruge kohe.', 286),
  ('text_287', 'Записать ребёнка', 'CTA', 'Записать ребёнка', 'Register my child', 'Registreeri laps', 287),
  ('text_288', 'Задать вопрос', 'CTA', 'Задать вопрос', 'Ask a question', 'Küsi küsimus', 288),
  ('text_289', 'Или звоните:', 'CTA', 'Или звоните:', 'Or call us:', 'Või helista:', 289),
  ('text_290', 'Детские лагеря - Эстония', 'Футер / кнопки', 'Детские лагеря - Эстония', 'Kids Camps - Estonia', 'Laste laagrid - Eesti', 290),
  ('text_291', 'Серфинг-школа и летние лагеря...', 'Футер / кнопки', 'Серфинг-школа и летние лагеря для детей в Таллине. Пляж Штромка. С 2017 года.', 'Surf school and summer camps for children in Tallinn. Stroomi Beach. Since 2017.', 'Surfamise kool ja suvelaagrid lastele Tallinnas. Stroomi rand. Alates 2017.', 291),
  ('text_292', 'Контакты', 'Футер / кнопки', 'Контакты', 'Contacts', 'Kontaktid', 292),
  ('text_293', 'Ссылки', 'Футер / кнопки', 'Ссылки', 'Links', 'Lingid', 293),
  ('text_294', 'Записаться', 'Футер / кнопки', 'Записаться', 'Register', 'Registreeru', 294),
  ('text_295', 'ALT - жилеты Stroomi', 'SEO / изображения', 'Дети в спасательных жилетах на Stroomi rand', 'Children in life jackets at Stroomi Beach', 'Lapsed paastevestides Stroomi rannas', 295),
  ('text_296', 'ALT - лагерь на воде', 'SEO / изображения', 'Детский серфинг лагерь на воде в Таллине', 'Kids surf camp on the water in Tallinn', 'Laste surfilaager vees Tallinnas', 296),
  ('text_297', 'ALT - инструкторы', 'SEO / изображения', 'Инструкторы Time to Surf с детьми', 'Time to Surf instructors with children', 'Time to Surf juhendajad lastega', 297),
  ('text_298', 'ALT - малая группа', 'SEO / изображения', 'Малая группа детей на пляже Stroomi', 'Small group of children at Stroomi Beach', 'Vaike lastegrupp Stroomi rannas', 298),
  ('text_299', 'Галерея - слово фото', 'Галерея', 'фото', 'photos', 'fotot', 299),
  ('text_300', 'Галерея - видео в подборке', 'Галерея', 'видео в подборке', 'videos in the set', 'videot valikus', 300),
  ('text_301', 'Локация - контактная строка', 'Локация', '+372 55512872 (Андрей)
Telegram: @Andrei_Time_to_Surf
info@timetosurf.ee', '+372 55512872 (Andrei)
Telegram: @Andrei_Time_to_Surf
info@timetosurf.ee', '+372 55512872 (Andrei)
Telegram: @Andrei_Time_to_Surf
info@timetosurf.ee', 301),
  ('text_302', 'CTA - текст перед ближайшей сменой', 'CTA', 'Мы работаем в малых группах, чтобы каждый ребёнок получил внимание инструктора. Ближайшая смена:', 'We work in small groups so every child gets instructor attention. Next session:', 'Töötame väikestes gruppides, et iga laps saaks juhendaja tähelepanu. Järgmine vahetus:', 302),
  ('text_303', 'Hero - слово от перед ценой', 'Hero / доверие', 'от', 'from', 'alates', 303),
  ('text_304', 'Hero - слово из в счётчике мест', 'Hero / доверие', 'из', 'of', '/', 304),
  ('text_305', 'Hero - места занято и ближайшая смена', 'Hero / доверие', 'мест занято - Ближайшая смена', 'spots taken - Next:', 'kohta täidetud - Järgmine vahetus', 305)
on conflict (key) do update set label=excluded.label, group_name=excluded.group_name, value_ru=excluded.value_ru, value_en=excluded.value_en, value_et=excluded.value_et, sort_order=excluded.sort_order, updated_at=now();

-- Checks
select id, sort_order, dates, leaders_ru, leaders_en, leaders_et from public.camp_sessions order by sort_order, id;
select key, value_ru, value_en, value_et from public.site_content where key in ('text_214','text_218','text_229','text_232','text_235','text_305') order by key;